name: PMD Scan

on: pull_request

jobs:
  pmd:
                    
    runs-on: ubuntu-latest
                          
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd -d ./src/main/java -R category/apex/design.xml -f text
